/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    tenants: Tenant;
    videocache__users: Videocache_User;
    videocache__videos: Videocache_Video;
    carshowcase__pages: Carshowcase_Page;
    carshowcase__images: Carshowcase_Image;
    carshowcase__car_albums: Carshowcase_CarAlbum;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {
    carshowcase__footer: Carshowcase_Footer;
    carshowcase__header: Carshowcase_Header;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  username?: string | null;
  roles: ('super-admin' | 'customer')[];
  tenants?:
    | {
        tenant?: (string | null) | Tenant;
        roles: ('admin' | 'user')[];
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: string;
  name?: string | null;
  slug: string;
  domains?:
    | {
        domain?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videocache__users".
 */
export interface Videocache_User {
  id: string;
  username: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videocache__videos".
 */
export interface Videocache_Video {
  id: string;
  owner: string | Videocache_User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carshowcase__pages".
 */
export interface Carshowcase_Page {
  id: string;
  slug: string;
  metaData?: {
    title?: string | null;
    description?: string | null;
  };
  content?:
    | (
        | {
            heroText?: {
              line1?: string | null;
              line2?: string | null;
            };
            heroImage?: (string | null) | Carshowcase_Image;
            cta?: {
              ctaText?: string | null;
              ctaLink?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'carshowcase__hero';
          }
        | {
            label?: string | null;
            partners?:
              | {
                  name?: string | null;
                  logo?: string | Carshowcase_Image | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'carshowcase__partners';
          }
        | {
            label?: string | null;
            links?:
              | {
                  name?: string | null;
                  url?: string | null;
                  logo?: string | Carshowcase_Image | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'carshowcase__social_links';
          }
        | {
            label?: string | null;
            albums?: (string | Carshowcase_CarAlbum)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'carshowcase__car_album_cards';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carshowcase__images".
 */
export interface Carshowcase_Image {
  id: string;
  altText?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    mid?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carshowcase__car_albums".
 */
export interface Carshowcase_CarAlbum {
  id: string;
  slug?: string | null;
  metaData?: {
    title?: string | null;
    description?: string | null;
  };
  backgroundImage?: string | Carshowcase_Image | null;
  cars?:
    | {
        modelName?: string | null;
        image?: string | Carshowcase_Image | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'videocache__users';
        value: string | Videocache_User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carshowcase__footer".
 */
export interface Carshowcase_Footer {
  id: string;
  copyrightNotice: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carshowcase__header".
 */
export interface Carshowcase_Header {
  id: string;
  companyName?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}